query getCoreShopProductsInCategory($categoryId: Int!) {
    CoreShopProducts(productListing: {category: {categoryId: $categoryId}}) {
    ... on CoreShopProductsResult {
        products {
        totalCount,
        edges {
            node {
            id
            name
            images {
                ... on asset {
                fullpath
                }
            }
            price: wholesalePrice
            shortDescription
            }
        }
        }
    }
    ... on CoreShopError {
        message
    }
    }
}